add showNextQuestion function
girlsjs/zadanie-quiz pull request #26
Opened 2019-09-02 19:59 UTC by karotella

2019-09-02 21:20 UTC, dar-puch requested changes
Trzeba tu zmienić te dwie rzeczy bo są błędy w konsoli. Reszta jest super i będzie śmigać

2019-09-02 21:20 UTC, dar-puch commented on quiz.js
> +  var currentQuestion = i;
i jest niezdefiniowane. Jako że mamy podać tu wartość początkową, proponuję zmienić na 0, wtedy zaczniemy od pierwszego pytania.

2019-09-02 21:20 UTC, dar-puch commented on quiz.js
> +    showQuestion(currentQuestion + 1);
Tu jest dobry moment, żeby przesunąć się do następnego pytania w zmiennej currentQuestion. Niech w tym miejscu ona się zwiększa o 1. Bez tego nextButton nigdy nie zniknie

2019-09-03 18:04 UTC, karotella commented on quiz.js
> +  var currentQuestion = i;
No właśnie błąd widziałam i zastanawiałam się, czy już mogę ustawiać tą początkową wartość w tym miejscu. Zmienione. :)

2019-09-03 18:04 UTC, karotella commented on quiz.js
> +    showQuestion(currentQuestion + 1);
Faktycznie o tym przesunięciu zapomniałam, dzięki! Dodałam. :)

2019-09-04 19:37 UTC, dar-puch approved these changes

2019-09-04 19:39 UTC, merged