restart quizu
girlsjs/zadanie-quiz pull request #35
Opened 2019-09-06 14:41 UTC by barbaramistrz

Trochę łopatologicznie i może na około zrobiłam ten powrót do radiogroup - jak warto poprawić to proszę o wskazówkę!

2019-09-07 13:26 UTC, dar-puch requested changes
Świetnie. Co prawda wymagam zmian ale to przez zderzenie z innym zadaniem.

2019-09-07 13:26 UTC, dar-puch commented on quiz.js
>        <p>${contentText}</p>
Tutaj, wewnątrz template literal możesz dopisać znacznik button, razem z klasą i tekstem, tak jak w html.
Daj mu jakieś id albo klasę inną niż next (np last).  W tym drugim przypadku last nie byłby ostylowany, dlatego trzeba dodać w css dla styli button.next jeszcze selektor button.last (po przecinku)

2019-09-07 13:26 UTC, dar-puch commented on quiz.js
> +    lastButton.style.display = 'block';
A tutaj dać mu event listener. Manipulacja widzialnością w ogóle nie jest potrzebna, ponieważ przy restarcie quizu cały main zostanie "zaorany" razem z buttonem. Ta zmiana, przesuwająca button do main jest już zrobiona w innym zadaniu ale w momencie pisania przez Ciebie kodu nie była jeszcze saclona. Teraz jest, więc Twój kod można już uprościć.

2019-09-07 13:26 UTC, dar-puch commented on quiz.js
> +    lastButton.style.display = 'none';
dwie powyższe linie można usunąć, z powodu, o którym pisałam w poprzednim komentarzu

2019-09-07 13:26 UTC, dar-puch commented on quiz.js
> +    `
świetnie, że pomyślałaś o dostosowaniu tej funkcji, żeby działała poprawnie po Twoich zmianach 👍 . Tak, tu po prostu musimy wkleić zawartość maina taką, jak w html. Index.html się zmienił, bo ma teraz przycisk "Dalej" w main, więc zajrzyj tam teraz. Jedyne co, to zawartość radiogroup (te wszystkie trzy inputy) możesz usunąć, bo funkcja showAnswers powinna dodawać je dynamicznie (mam nadzieję, że tak będzie). Wtedy w index.html też wyczyścimy tę część więc ty możesz to zrobić już teraz w funkcji startQuiz.

2019-09-08 10:17 UTC, dar-puch commented on quiz.js
> +    lastButton.addEventListener('click', startQuiz);
ta linia niech przejdzie do startQuiz

2019-09-09 16:07 UTC, barbaramistrz commented
Dzięki! Tylko pozmieniałam na tym samym pliku, bo nie wiedziałam jak zmergować mój z aktualnym. Chyba powinnam była jakoś wyjść z branch issue-1? git pull upstream dawał taką wiadomość: You asked to pull from the remote 'upstream', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.
****

2019-09-10 08:52 UTC, dar-puch approved these changes

2019-09-10 08:52 UTC, merged