#44 fix last question displaying
girlsjs/zadanie-quiz pull request #45
Opened 2019-09-19 21:51 UTC by bonsa

Naprawilam wyświetlanie ostatniego pytania. Przy okazji usunełam troche zbędnego kodu i poprawilam formatowanie.

2019-09-20 19:15 UTC, dar-puch commented
Muszę mieć chwilę, żeby przetestować. Mam pewne podejrzenia...

2019-09-20 19:16 UTC, bonsa commented
Super :)!

2019-09-21 07:08 UTC, dar-puch commented
Już widzę. Weryfikowane są 3 pytania z 4, przy ostatnim nie ma weryfikacji

2019-09-21 07:12 UTC, bonsa commented
Ok. Poprawic to w ramach tego zadania? :)

On Sat, 21 Sep 2019 at 09:08, dar-puch <notifications@github.com> wrote:

> Już widzę. Weryfikowane są 3 pytania z 4, przy ostatnim nie ma weryfikacji
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/girlsjs/zadanie-quiz/pull/45?email_source=notifications&email_token=AADJHPVBLLHFW7X4MASCFOLQKXB6XA5CNFSM4IYQNSF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7IMEGY#issuecomment-533774875>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADJHPTFX53WEQG4SU2CASLQKXB6XANCNFSM4IYQNSFQ>
> .
>

2019-09-21 08:24 UTC, dar-puch requested changes
Podoba mi się Twoje rozwiązanie, jest proste, bez nadmiernej ifologii.  Popraw tylko ten brak weryfikacji

2019-09-21 08:24 UTC, dar-puch commented on quiz.js
> -
Uporządkowanie tego to dobry pomysł

2019-09-21 08:24 UTC, dar-puch commented on quiz.js
> -
Nie ma weryfikacji

2019-09-21 15:05 UTC, bonsa commented on quiz.js
> -
dodane!

2019-09-22 14:35 UTC, dar-puch approved these changes

2019-09-22 14:35 UTC, merged